# Generated by Django 5.1.6 on 2025-02-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0002_charityevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('author', models.CharField(default='Admin', max_length=255)),
                ('comments_count', models.IntegerField(default=0)),
            ],
        ),
    ]
