# Generated by Django 5.1.6 on 2025-02-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0004_blogpost_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('content', models.TextField()),
                ('rating', models.IntegerField(default=5)),
            ],
        ),
    ]
