# Generated by Django 5.1.6 on 2025-03-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0005_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
