# Generated by Django 5.1.6 on 2025-03-02 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0006_schoolgallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolGallery',
            new_name='CharityGallery',
        ),
    ]
