# Generated by Django 5.1.6 on 2025-03-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0008_contactmessage_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('skills', models.TextField()),
                ('availability', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
