# Generated by Django 5.0.2 on 2025-03-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0011_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='charitygallery',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='gallery/videos/'),
        ),
    ]
