# Generated by Django 5.0.2 on 2025-03-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0012_charitygallery_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitygallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
